# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Music"
url = "/music"
weight = 2

[[main]]
name = "Practice"
parent = "Music"
url = "/music/blog"
weight = 1

[[main]]
name = "Piano Pieces"
parent = "Music"
url = "/music/piano-pieces"
weight = 2

[[main]]
name = "Writing"
weight = 3

[[main]]
name = "Kell & Co"
parent = "Writing"
url = "/writing/kell-and-co"
weight = 1

[[main]]
name = "Short Stories"
parent = "Writing"
url = "/writing/blog"
weight = 2


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy-policy"
weight = 2
